### ISSUE TITLE
Wrong crop

### ISSUE THREAD

**Issue by Neoziox** [Jako/ImagePlus#110]
First, I have a minimal size on my TV parameter. But, whatever I choose as an image, it always tells me that the image is too small (parameter: 2000 × 500, I choose an image 4000 × 1000, but it's too small for him). So, I deleted the minimal sizes.

But now, when I choose an image, this one is automatically cropped but in a wrong way (a tiny zone of the image). If I crop manually, it's still bad cropping. I don't know how can I fix this.

----------
Image+ 2.8.9 and MODX 3.0.1

**Comment by Neoziox** [comment]
Hi!

No idea? It's very annoying 🙁 and I cannot use the TV

**Comment by Jako** [comment]
Please check the fix in the 2.9.0 package in https://github.com/Jako/ImagePlus/tree/master/_packages

By the way: I am working on my open source extras in my spare time. Please don't expect a quick fix for my open source extras. If you like my work: there is a donate button.

**Comment by Jako** [comment]
This is finally solved in 2.9.1

**Comment by mediakracht** [comment]
I am sorry to reopen this issue. I am using Image+ 2.9.1 and Modx 3.0.1 but I still have the following problem:

"whatever I choose as an image, it always tells me that the image is too small (parameter: 2000 × 500, I choose an image 4000 × 1000, but it's too small for him)"
